// Renderer-facing wrappers around the autogenerated contract clients.
// The contracts take object payloads (one shape for the schema, one
// shape across the wire); these wrappers expose the ergonomic
// positional-argument signatures the renderer hooks call against. New
// IPC entries get a contract line and one entry here; the schema +
// runtime parse is wired automatically.
import { buildClient } from "@shared/ipc/buildClient";
import { dialogContract } from "@shared/ipc/modules/dialog";
import { diffsContract } from "@shared/ipc/modules/diffs";
import { fsContract } from "@shared/ipc/modules/fs";
import { ghContract } from "@shared/ipc/modules/gh";
import { globalConfigContract } from "@shared/ipc/modules/globalConfig";
import { reposContract } from "@shared/ipc/modules/repos";
import { runtimeContract } from "@shared/ipc/modules/runtime";
import { windowContract } from "@shared/ipc/modules/window";
import type { GlobalConfig, RefExpr, Theme } from "@shared/schemas";

const dialogClient = buildClient(dialogContract);
const diffsClient = buildClient(diffsContract);
const fsClient = buildClient(fsContract);
const ghClient = buildClient(ghContract);
const globalConfigClient = buildClient(globalConfigContract);
const reposClient = buildClient(reposContract);
const runtimeClient = buildClient(runtimeContract);
const windowClient = buildClient(windowContract);

export const runtime = {
  info: () => runtimeClient.info(),
  setTheme: (theme: Theme) => runtimeClient.setTheme({ theme }),
} as const;

export const fs = {
  listDirectory: (path: string) => fsClient.listDirectory({ path }),
  isGitRepo: (path: string) => fsClient.isGitRepo({ path }),
  scanForGitRepos: (path: string) => fsClient.scanForGitRepos({ path }),
} as const;

export const dialog = {
  pickFolder: (options?: { title?: string; buttonLabel?: string }) =>
    dialogClient.pickFolder(options),
} as const;

export const repos = {
  list: () => reposClient.list(),
  add: (path: string) => reposClient.add({ path }),
  remove: (id: string) => reposClient.remove({ id }),
  branches: (repoId: string) => reposClient.branches({ repoId }),
  recentCommits: (repoId: string) => reposClient.recentCommits({ repoId }),
  worktrees: (repoId: string) => reposClient.worktrees({ repoId }),
} as const;

export const diffs = {
  list: (repoId: string) => diffsClient.list({ repoId }),
  create: (input: {
    repoId: string;
    name?: string;
    left: RefExpr;
    right: RefExpr;
    rightWorktreePath?: string;
  }) => diffsClient.create(input),
  get: (input: { repoId: string; diffId: string }) => diffsClient.get(input),
  delete: (input: { repoId: string; diffId: string }) => diffsClient.delete(input),
  resolve: (input: { repoId: string; diffId: string }) => diffsClient.resolve(input),
  fullTree: (input: { repoId: string; diffId: string }) => diffsClient.fullTree(input),
  setReviewed: (input: { repoId: string; diffId: string; path: string; reviewed: boolean }) =>
    diffsClient.setReviewed(input),
  setPin: (input: { repoId: string; diffId: string; pinned: boolean }) => diffsClient.setPin(input),
  readFile: (input: { repoId: string; diffId: string; path: string; side: "left" | "right" }) =>
    diffsClient.readFile(input),
  readReviewedSnapshot: (input: { repoId: string; diffId: string; path: string }) =>
    diffsClient.readReviewedSnapshot(input),
  writeFile: (input: { repoId: string; diffId: string; path: string; content: string }) =>
    diffsClient.writeFile(input),
  createFromPullRequest: (input: { repoId: string; number: number }) =>
    diffsClient.createFromPullRequest(input),
} as const;

export const gh = {
  readiness: () => ghClient.readiness(),
  listPullRequests: (repoId: string) => ghClient.listPullRequests({ repoId }),
} as const;

export const globalConfig = {
  read: () => globalConfigClient.read(),
  write: (config: GlobalConfig) => globalConfigClient.write({ config }),
} as const;

export const windowApi = {
  onFocused: windowClient.focused,
  onBlurred: windowClient.blurred,
} as const;
